development:
  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      fork: mainnet
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: mainnet-fork
    name: Ganache-CLI (Mainnet Fork)
    timeout: 180
  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 5
      fork: goerli
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: goerli-fork
    name: goerli-fork
    timeout: 180
  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 1337
      fork: http://127.0.0.1:7777
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: local-fork
    name: local-fork
    explorer: https://api.etherscan.io/api
    timeout: 180
